let Data = [
    {
      "id": 1,
      "title": "JANAKI AIRWAYS",
      "type": "Travell & Tourisim",
      "image": "/images/airways.png",
      "script": "HTML, CSS, Bootstrap,React",
      "link": "https://janaki-airways.vercel.app/",
    },
    {
      "id": 2,
      "title": "KARKHA",
      "type": "Innovative Education",    
      "image": "/images/karkhana.png",
      "script": "HTML, CSS, Bootstrap,React",
      "link": "",
    },
    {
      "id": 3,
      "title": "JANAKI COLLECTION",
      "type": "Online Shopping Store",
      "image": "/images/collection.png",
      "script": "HTML, CSS, Bootstrap,React",
      "link": "",
    },
    {
      "id": 4,
      "title": "The Himalayan Times",
      "type": "News Portal",
      "image": "/images/news.png",
      "link": "https://news-umber-chi.vercel.app/",
      "script": "HTML, CSS, Bootstrap,React",
    },
    {
      "id": 5,
      "title": "ZAY",
      "type": "Online Shopping Store",
      "image": "/images/zay.png",
      "link": "https://e-commerce-kappa-lyart.vercel.app/",
      "script": "HTML, CSS",
    },
    {
      "id": 6,
      "title": "VILLA",
      "type": "Real States Business",
      "image": "/images/villa.png",
      "link": "",
      "script": "HTML, CSS",
    },
    {
      "id": 7,
      "title": "Green Crops",
      "type": "",
      "image": "/images/greencrops.png",
      "link": "",
      "script": "HTML, CSS",
    },
    {
      "id": 8,
      "title": "ME",
      "type": "",
      "image": "/images/me.png",
      "link": "",
      "script": "HTML, CSS, Bootstrap",
    },
    {
      "id": 9,
      "title": "BroadWay Infosys",
      "type": "Skilled Human Resources Management",
      "image": "/images/broadway.png",
      "link": "",
      "script": "HTML, CSS, Bootstrap",
    },
  ]
export default Data;